name = "coop_bc"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:generic"]
  enabled = true
  
[builders."docker:generic".build_args]
build_image = "golang:alpine"
run_image = "scratch"

[builders."docker:go"]
enabled = true

[builders."exec:go"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name = "bc"
instances = { min = 1, max = 200, default = 1 }





